### ISSUE TITLE
Getting SWDIO direction on additional pin for an isolated/level shifting interface

### ISSUE THREAD

**Issue by OpusElectronics** [wuxx/nanoDAP-HS#10]
Hello,

nanoDAP-HS adapters are great, but they are limited to 3.3V interfacing.
I would like to design a small interface board for isolation and level shifting of the JTAG/SWD signals.
For JTAG, it is no problem, but for SWD, as the SWDIO signal is bidirectional, it is more problematic.
Classic bidirectional isolators or level shifters do not work that great for SWD. So ideally, it would be great if the firmware in SWD mode would output the direction of SWDIO (for instance: 0 = OUT, 1 = IN) on a separate pin (for instance TDI or TDO which are not used currently for SWD) to control the direction on the interface board.

Let me know if this is possible or if we can have access to the firmware source code.

**Comment by wuxx** [comment]
[DAPLink.zip](https://github.com/wuxx/nanoDAP-HS/files/10350750/DAPLink.zip)
hello，here is the source code， please check it.
