### ISSUE TITLE
可以增加ESP32系列的自动下载功能吗？

### ISSUE THREAD

**Issue by 203Null** [wuxx/nanoDAP-HS#6]
可以把Boot和EN映射到两个脚上

**Comment by wuxx** [comment]
针对ESP32全系列芯片，已经开发完成了ESPLink，可支持下载调试功能。
https://github.com/wuxx/ESPLink

**Comment by 203Null** [comment]
> 针对ESP32全系列芯片，已经开发完成了ESPLink，可支持自动下载、调试等功能。 https://github.com/wuxx/ESPLink

就是看到了那个才来问下，毕竟都是jtag+uart, nanoDAP还多带个SWO。 如果nanoDAP能自动下载相当于合一了。

**Comment by wuxx** [comment]
自动下载需要硬件上增加电路才可以，普通IO无法实现

**Comment by 203Null** [comment]
![image](https://user-images.githubusercontent.com/19933093/152939765-ef6b3913-5ae1-40b9-9dca-5d1294d2b618.png)
利用软件识别DTR与RTS然后上下拉EN和Boot不可行吗？

**Comment by wuxx** [comment]
可以，不过恐怕你还得修改esptool.py 源码，或者自己单独在调用esptool.py前用自己的程序控制一下IO

**Comment by 203Null** [comment]
> 可以，不过恐怕你还得修改esptool.py 源码，或者自己单独在调用esptool.py前用自己的程序控制一下IO

好的了解了
